### ISSUE TITLE
EditNotificationService not called

### ISSUE THREAD

**Issue by mbalajee** [phunware/maas-engagement-android-sdk#14]
**Manifest**:
      service
            android:name=".phunwarebeacon.EditNotificationService"
            android:exported="false"> // Also tried with exported true
            intent-filter
                action android:name="com.phunware.Engagement.EDIT_NOTIFICATION" 
            intent-filter
        service

**MessageInterceptor**:
**addMessageListener() is commented.**  Not required so commented it.  

With this code, none of the callback in EditNotificationSerivce are called.  Tried when both app is in background, foreground and not running status.  Can someone pls help with this?

**Requirement**:
Add a pending intent to notification builder.  So when user taps on a notification, launch a specific activity.

**Comment by mbalajee** [comment]
Can you please look into this issue?  It is blocking us from moving forward.

Issue: Dynamic SQL Injection - Security vulnerability
Affected class:
LogMessageProvider
SelectionBuilder
MappingProvider

Attaching screenshot
<img width="869" alt="screen shot 2019-02-12 at 9 15 27 am" src="https://user-images.githubusercontent.com/17508872/52641584-2fed2e80-2ea7-11e9-8e22-b3231a707865.png">



<img width="910" alt="screen shot 2019-02-12 at 9 15 34 am" src="https://user-images.githubusercontent.com/17508872/52641602-38de0000-2ea7-11e9-95eb-b4cc70a73321.png">



<img width="898" alt="screen shot 2019-02-12 at 9 15 46 am" src="https://user-images.githubusercontent.com/17508872/52641610-3c718700-2ea7-11e9-8844-1f1c1740e407.png">

**Comment by avakkachen** [comment]
Closing this issue. Will reopen if this is still an issue.
