### ISSUE TITLE
Security vulnerability - Dynamic SQL injection

### ISSUE THREAD

**Issue by mbalajee** [phunware/maas-engagement-android-sdk#15]
Can you please look into this issue? It is blocking us from moving forward.

Issue: Dynamic SQL Injection - Security vulnerability

**Affected class**:
LogMessageProvider
SelectionBuilder
MappingProvider

Attaching screenshot

<img width="869" alt="screen shot 2019-02-12 at 9 15 27 am" src="https://user-images.githubusercontent.com/17508872/52641682-688d0800-2ea7-11e9-96ef-bd29e85ddf05.png">

<img width="910" alt="screen shot 2019-02-12 at 9 15 34 am" src="https://user-images.githubusercontent.com/17508872/52641691-6c208f00-2ea7-11e9-9cc5-79eec798bf01.png">

<img width="898" alt="screen shot 2019-02-12 at 9 15 46 am" src="https://user-images.githubusercontent.com/17508872/52641695-6f1b7f80-2ea7-11e9-8082-7224ed06113c.png">

**Comment by avakkachen** [comment]
Mapping SDK DB is internal to the app using it and is not exposed to external applications. No other apps on the same device can access this DB. So an SQL injection attack is not possible here.
